"""empty message

Revision ID: 10daafe7ba13
Revises: 
Create Date: 2023-09-17 13:41:13.612374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10daafe7ba13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('burritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=64), nullable=True),
    sa.Column('customer_phone_number', sa.String(length=64), nullable=True),
    sa.Column('customer_street_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('burrito_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('burrito_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['burrito_id'], ['burritos.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('burrito_orders')
    op.drop_table('orders')
    op.drop_table('burritos')
    # ### end Alembic commands ###
