"""empty message

Revision ID: 312b6c4ca7cf
Revises: 36d8cff20492
Create Date: 2023-09-17 22:21:55.937377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312b6c4ca7cf'
down_revision = '36d8cff20492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('burrito_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('burrito_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['burrito_id'], ['burritos.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('burrito_orders')
    # ### end Alembic commands ###
